branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: project starter code2
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin2
  sc: git
  workspace_type: Application
